# Generated by Django 6.0.7 on 2026-07-15 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_medida', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco por Medida')),
                ('preco_atacado_meio_kilo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco Atacado (500g)')),
                ('preco_atacado_kilo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco Atacado (1kg)')),
                ('preco_bruto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('validade', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
