# Generated by Django 6.0.7 on 2026-07-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('tempero', 'Tempero'), ('alho', 'Alho'), ('cebola', 'Cebola'), ('pimenta', 'Pimenta'), ('pimenta_granel', 'Pimenta a Granel'), ('cha', 'Chá'), ('mel', 'Mel'), ('pre_treino', 'Pré-Treino')], max_length=20)),
                ('preco_medida', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_atacado_meio_kilo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_atacado_kilo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_bruto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField(default=0)),
                ('validade', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='movimentacoes.produto')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
